server:
  port: 9102

spring:
  application:
    name: simple-nacos-feign-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true  #允许一样的beanName